// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type BuyTokenInput struct {
	SaleID   int   `json:"saleId"`
	Quantity int32 `json:"quantity"`
}

type CreateLandTokenInput struct {
	Name                 string  `json:"name"`
	TotalTokens          int32   `json:"totalTokens"`
	CurrentPrice         float64 `json:"currentPrice"`
	PropertyType         string  `json:"propertyType"`
	PropertySize         float64 `json:"propertySize"`
	PropertySizeUnit     string  `json:"propertySizeUnit"`
	Landmark             string  `json:"landmark"`
	DistanceFromLandmark float64 `json:"distanceFromLandmark"`
	DistanceUnit         string  `json:"distanceUnit"`
	PropertyDescription  string  `json:"propertyDescription"`
	Latitude             string  `json:"latitude"`
	Longitude            string  `json:"longitude"`
}

type CreatePriceInput struct {
	Date  time.Time `json:"date"`
	Value float64   `json:"value"`
}

type CreateSaleInput struct {
	LandTokenID int32   `json:"landTokenId"`
	Quantity    int32   `json:"quantity"`
	Price       float64 `json:"price"`
}

type CreateUserInput struct {
	PublicKey string `json:"publicKey"`
	Username  string `json:"username"`
	Phone     string `json:"phone"`
	Email     string `json:"email"`
}

type LandToken struct {
	LandID               int32     `json:"landId"`
	Name                 string    `json:"name"`
	TotalTokens          int32     `json:"totalTokens"`
	CreatedAt            time.Time `json:"createdAt"`
	UpdatedAt            time.Time `json:"updatedAt"`
	CurrentPrice         float64   `json:"currentPrice"`
	Prices               []*Price  `json:"prices"`
	PropertyType         string    `json:"propertyType"`
	PropertySize         float64   `json:"propertySize"`
	PropertySizeUnit     string    `json:"propertySizeUnit"`
	Landmark             string    `json:"landmark"`
	DistanceFromLandmark float64   `json:"distanceFromLandmark"`
	DistanceUnit         string    `json:"distanceUnit"`
	PropertyDescription  string    `json:"propertyDescription"`
	Latitude             string    `json:"latitude"`
	Longitude            string    `json:"longitude"`
}

type LoginResponse struct {
	Token string `json:"token"`
	User  *User  `json:"User"`
}

type Mutation struct {
}

type OwnedToken struct {
	ID        int        `json:"id"`
	LandToken *LandToken `json:"landToken"`
	Quantity  int32      `json:"quantity"`
}

type Price struct {
	ID    int       `json:"id"`
	Date  time.Time `json:"date"`
	Value float64   `json:"value"`
}

type Query struct {
}

type Role struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type Sale struct {
	ID        int        `json:"id"`
	LandToken *LandToken `json:"landToken"`
	Quantity  int32      `json:"quantity"`
	Price     float64    `json:"price"`
	Seller    *User      `json:"seller"`
	CreatedAt time.Time  `json:"createdAt"`
}

type TransactedToken struct {
	ID        int        `json:"id"`
	LandToken *LandToken `json:"landToken"`
	Quantity  int32      `json:"quantity"`
	Price     float64    `json:"price"`
	From      *User      `json:"from,omitempty"`
	To        *User      `json:"to,omitempty"`
	CreatedAt time.Time  `json:"createdAt"`
}

type UpdateSaleInput struct {
	Quantity int32   `json:"quantity"`
	Price    float64 `json:"price"`
}

type UpdateUserInput struct {
	Username *string `json:"username,omitempty"`
	Phone    *string `json:"phone,omitempty"`
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

type User struct {
	PublicKey    string             `json:"publicKey"`
	Username     string             `json:"username"`
	Phone        string             `json:"phone"`
	Email        string             `json:"email"`
	Roles        []*Role            `json:"roles"`
	CreatedAt    time.Time          `json:"createdAt"`
	UpdatedAt    time.Time          `json:"updatedAt"`
	Watchlist    []*LandToken       `json:"watchlist"`
	OwnedTokens  []*OwnedToken      `json:"ownedTokens"`
	BoughtTokens []*TransactedToken `json:"boughtTokens"`
	Sales        []*Sale            `json:"sales"`
	SoldTokens   []*TransactedToken `json:"soldTokens"`
}
