const transactions = [
  {
    tokenCode: "KTM-1154W5",
    propertyLocation: "Kathmandu Ward 1",
    propertyType: "Commercial",
    transactionDate: "2025-01-01",
    transactionType: "sold",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: 50,
  },
  {
    tokenCode: "KTM-1154W6",
    propertyLocation: "Kathmandu Ward 2",
    propertyType: "Residential",
    transactionDate: "2025-02-01",
    transactionType: "Sold",
    amount: 20,
    tokenPrice: 500,
    profitLoss: -20,
  },
  {
    tokenCode: "KTM-1154W7",
    propertyLocation: "Kathmandu Ward 3",
    propertyType: "Agricultural",
    transactionDate: "2025-01-01",
    transactionType: "Bought",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: 10,
  },
  {
    tokenCode: "KTM-1154W8",
    propertyLocation: "Kathmandu Ward 4",
    propertyType: "Commercial",
    transactionDate: "2025-01-01",
    transactionType: "Bought",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: 20,
  },
  {
    tokenCode: "KTM-1154W9",
    propertyLocation: "Kathmandu Ward 5",
    propertyType: "Recreational",
    transactionDate: "2025-01-01",
    transactionType: "sold",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: -10,
  },
  {
    tokenCode: "KTM-1154W10",
    propertyLocation: "Kathmandu Ward 6",
    propertyType: "Agricultural",
    transactionDate: "2025-01-01",
    transactionType: "Bought",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: 14,
  },
  {
    tokenCode: "KTM-1154W11",
    propertyLocation: "Kathmandu Ward 7",
    propertyType: "Commercial",
    transactionDate: "2025-01-01",
    transactionType: "Bought",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: -11,
  },
  {
    tokenCode: "KTM-1154W12",
    propertyLocation: "Kathmandu Ward 8",
    propertyType: "Recreational",
    transactionDate: "2025-01-01",
    transactionType: "Bought",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: -5,
  },
  {
    tokenCode: "KTM-1154W13",
    propertyLocation: "Kathmandu Ward 9",
    propertyType: "Agricultural",
    transactionDate: "2025-01-01",
    transactionType: "sold",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: 12,
  },
  {
    tokenCode: "KTM-1154W14",
    propertyLocation: "Kathmandu Ward 8",
    propertyType: "Commercial",
    transactionDate: "2025-01-01",
    transactionType: "Bought",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: 5,
  },
  {
    tokenCode: "KTM-1154W15",
    propertyLocation: "Kathmandu Ward 7",
    propertyType: "Agricultural",
    transactionDate: "2025-01-01",
    transactionType: "Bought",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: -5,
  },
  {
    tokenCode: "KTM-1154W16",
    propertyLocation: "Kathmandu Ward 6",
    propertyType: "Recreational",
    transactionDate: "2025-01-01",
    transactionType: "Bought",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: 21,
  },
  {
    tokenCode: "KTM-1154W17",
    propertyLocation: "Kathmandu Ward 5",
    propertyType: "Commercial",
    transactionDate: "2025-01-01",
    transactionType: "Bought",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: -8,
  },
  {
    tokenCode: "KTM-1154W18",
    propertyLocation: "Kathmandu Ward 4",
    propertyType: "Agricultural",
    transactionDate: "2025-01-01",
    transactionType: "sold",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: 12,
  },
  {
    tokenCode: "KTM-1154W19",
    propertyLocation: "Kathmandu Ward 3",
    propertyType: "Commercial",
    transactionDate: "2025-01-01",
    transactionType: "Bought",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: 11,
  },
  {
    tokenCode: "KTM-1154W20",
    propertyLocation: "Kathmandu Ward 2",
    propertyType: "Commercial",
    transactionDate: "2025-01-01",
    transactionType: "Bought",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: -11,
  },
  {
    tokenCode: "KTM-1154W21",
    propertyLocation: "Kathmandu Ward 11",
    propertyType: "Commercial",
    transactionDate: "2025-01-01",
    transactionType: "sold",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: -13,
  },
  {
    tokenCode: "KTM-1154W22",
    propertyLocation: "Kathmandu Ward 12",
    propertyType: "Agricultural",
    transactionDate: "2025-01-01",
    transactionType: "Bought",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: -20,
  },
  {
    tokenCode: "KTM-1154W23",
    propertyLocation: "Kathmandu Ward 13",
    propertyType: "Commercial",
    transactionDate: "2025-01-01",
    transactionType: "Bought",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: 7,
  },
  {
    tokenCode: "KTM-1154W24",
    propertyLocation: "Kathmandu Ward 14",
    propertyType: "Commercial",
    transactionDate: "2025-01-01",
    transactionType: "Bought",
    amount: 10,
    tokenPrice: 1000,
    profitLoss: -10,
  },
];
export default transactions;
