package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"database/sql"
	"fmt"
	"time"

	"github.com/ludeathfer/TerraTokens/backend/graph/model"
	"github.com/ludeathfer/TerraTokens/backend/middleware"
	"golang.org/x/crypto/bcrypt"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	db := r.Database

	// Start a transaction
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to start transaction: %w", err)
	}

	// Ensure rollback on error
	defer func() {
		if err != nil {
			_ = tx.Rollback()
		}
	}()

	// Insert the user
	query := `
		INSERT INTO users (public_key, username, phone, email)
		VALUES (?, ?, ?, ?)
	`
	_, err = tx.ExecContext(ctx, query, input.PublicKey, input.Username, input.Phone, input.Email)
	if err != nil {
		return nil, fmt.Errorf("failed to insert user: %w", err)
	}

	// Fetch the 'user' role
	role := &model.Role{}
	query = `SELECT id, name, description FROM roles WHERE name = 'user'`
	err = tx.QueryRowContext(ctx, query).Scan(&role.ID, &role.Name, &role.Description)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch user role: %w", err)
	}

	// Assign the 'user' role to the new user
	query = `INSERT INTO user_roles (user_public_key, role_id) VALUES (?, ?)`
	_, err = tx.ExecContext(ctx, query, input.PublicKey, role.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to assign user role: %w", err)
	}

	// Commit transaction
	if err = tx.Commit(); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	// Return the created user object
	user := &model.User{
		PublicKey: input.PublicKey,
		Username:  input.Username,
		Phone:     input.Phone,
		Email:     input.Email,
		CreatedAt: time.Now(),
		UpdatedAt: time.Now(),
		Roles:     []*model.Role{role},
	}
	return user, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, publicKey string, input model.UpdateUserInput) (*model.User, error) {
	db := r.Database

	// Start a transaction
	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to start transaction: %w", err)
	}

	defer func() {
		if err != nil {
			tx.Rollback()
		}
	}()

	// Update query
	query := `
		UPDATE users 
		SET updated_at = NOW()
		`
	args := []any{}

	if input.Username != nil {
		query += ", username = ?"
		args = append(args, input.Username)
	}

	if input.Phone != nil {
		query += ", phone = ?"
		args = append(args, input.Phone)
	}

	if input.Email != nil {
		query += ", email = ?"
		args = append(args, input.Email)
	}

	// Append password update only if provided
	if input.Password != nil {
		password := *input.Password

		hashedPassword, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
		if err != nil {
			return nil, fmt.Errorf("failed to hash password: %w", err)
		}

		query += ", password = ?"
		args = append(args, hashedPassword)
	}

	query += " WHERE public_key = ?"
	args = append(args, publicKey)

	// Execute update
	result, err := tx.ExecContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("failed to update user: %w", err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return nil, fmt.Errorf("failed to check affected rows: %w", err)
	}

	if rowsAffected == 0 {
		return nil, fmt.Errorf("user not found")
	}

	// Commit transaction
	if err = tx.Commit(); err != nil {
		return nil, fmt.Errorf("failed to commit transaction: %w", err)
	}

	user := &model.User{
		Username: *input.Username,
		Phone:    *input.Phone,
		Email:    *input.Email,
	}

	return user, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, publicKey string) (bool, error) {
	db := r.Database

	query := `DELETE FROM users WHERE public_key = ?`
	result, err := db.ExecContext(ctx, query, publicKey)
	if err != nil {
		return false, fmt.Errorf("failed to delete user: %w", err)
	}

	rowsAffected, err := result.RowsAffected()
	if err != nil {
		return false, fmt.Errorf("failed to check affected rows: %w", err)
	}

	if rowsAffected == 0 {
		return false, fmt.Errorf("user not found")
	}

	return true, nil
}

// CreateLandToken is the resolver for the createLandToken field.
func (r *mutationResolver) CreateLandToken(ctx context.Context, input model.CreateLandTokenInput) (*model.LandToken, error) {
	db := r.Database

	query := `
	UPDATE land_tokens
	SET
		current_price = ?,
		property_type = ?,
		property_size = ?,
		property_size_unit = ?,
		landmark = ?,
		distance_from_landmark = ?,
		distance_unit = ?,
		property_description = ?,
		latitude = ?,
		longitude = ?
	WHERE
    	name = ?;
		`
	_, err := db.ExecContext(ctx, query,
		input.CurrentPrice,
		input.PropertyType, input.PropertySize, input.PropertySizeUnit, input.Landmark,
		input.DistanceFromLandmark, input.DistanceUnit, input.PropertyDescription,
		input.Latitude, input.Longitude, input.Name,
	)

	if err != nil {
		return nil, fmt.Errorf("failed inserting into database: %v", err)
	}

	// Construct response object
	landToken := &model.LandToken{
		Name:                 input.Name,
		CreatedAt:            time.Now(),
		UpdatedAt:            time.Now(),
		CurrentPrice:         input.CurrentPrice,
		PropertyType:         input.PropertyType,
		PropertySize:         input.PropertySize,
		PropertySizeUnit:     input.PropertySizeUnit,
		Landmark:             input.Landmark,
		DistanceFromLandmark: input.DistanceFromLandmark,
		DistanceUnit:         input.DistanceUnit,
		PropertyDescription:  input.PropertyDescription,
		Latitude:             input.Latitude,
		Longitude:            input.Longitude,
	}

	return landToken, nil
}

// UpdateLandToken is the resolver for the updateLandToken field.
func (r *mutationResolver) UpdateLandToken(ctx context.Context, publicKey string, input model.CreateLandTokenInput) (*model.LandToken, error) {
	panic(fmt.Errorf("not implemented: UpdateLandToken - updateLandToken"))
}

// AddPriceToLandToken is the resolver for the addPriceToLandToken field.
func (r *mutationResolver) AddPriceToLandToken(ctx context.Context, publicKey string, input model.CreatePriceInput) (*model.LandToken, error) {
	panic(fmt.Errorf("not implemented: AddPriceToLandToken - addPriceToLandToken"))
}

// BuyToken is the resolver for the buyToken field.
func (r *mutationResolver) BuyToken(ctx context.Context, input model.BuyTokenInput) (*model.TransactedToken, error) {
	panic(fmt.Errorf("not implemented: BuyToken - buyToken"))
}

// UpdateSale is the resolver for the updateSale field.
func (r *mutationResolver) UpdateSale(ctx context.Context, id int, input model.UpdateSaleInput) (*model.Sale, error) {
	panic(fmt.Errorf("not implemented: UpdateSale - updateSale"))
}

// DeleteSale is the resolver for the deleteSale field.
func (r *mutationResolver) DeleteSale(ctx context.Context, id int) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteSale - deleteSale"))
}

// AddToWatchlist is the resolver for the addToWatchlist field.
func (r *mutationResolver) AddToWatchlist(ctx context.Context, publicKey string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: AddToWatchlist - addToWatchlist"))
}

// RemoveFromWatchlist is the resolver for the removeFromWatchlist field.
func (r *mutationResolver) RemoveFromWatchlist(ctx context.Context, publicKey string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: RemoveFromWatchlist - removeFromWatchlist"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, publicKey string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, publicKey string) (*model.LoginResponse, error) {
	db := r.Database

	query := `
		SELECT
			u.public_key, u.username, u.phone, u.email, u.created_at, u.updated_at,
			r.id, r.name, r.description
		FROM users u
		LEFT JOIN user_roles ur ON u.public_key = ur.user_public_key
		LEFT JOIN roles r ON ur.role_id = r.id
		WHERE u.public_key = ?
	`
	rows, err := db.QueryContext(ctx, query, publicKey)
	if err != nil {
		return nil, fmt.Errorf("invalid credentials: %w", err)
	}
	defer rows.Close()

	var user *model.User
	roleNames := []string{}
	for rows.Next() {
		user = &model.User{}
		role := &model.Role{}
		err := rows.Scan(&user.PublicKey, &user.Username, &user.Email, &user.Phone, &user.CreatedAt, &user.UpdatedAt, &role.ID, &role.Name, &role.Description)
		if err != nil {
			return nil, fmt.Errorf("failed to scan user: %w", err)
		}
		user.Roles = append(user.Roles, role)
		roleNames = append(roleNames, role.Name)
	}

	if user == nil {
		return nil, fmt.Errorf("invalid credentials")
	}

	token, err := middleware.GenerateToken(r.Config.JWT, user.PublicKey, roleNames)
	if err != nil {
		return nil, err
	}

	loginResponse := &model.LoginResponse{
		Token: token,
		User:  user,
	}

	return loginResponse, nil
}

// LandTokens is the resolver for the landTokens field.
func (r *queryResolver) LandTokens(ctx context.Context) ([]*model.LandToken, error) {
	db := r.Database // Assuming r.Database is your *sql.DB

	query := `
		SELECT land_id, name, total_tokens, created_at, updated_at, current_price, property_type, property_size, property_size_unit, landmark, distance_from_landmark, distance_unit, property_description, latitude, longitude
		FROM land_tokens;
	`

	rows, err := db.QueryContext(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("failed to query land tokens: %w", err)
	}
	defer rows.Close()

	var landTokens []*model.LandToken
	for rows.Next() {
		lt := &model.LandToken{}
		err := rows.Scan(
			&lt.LandID, &lt.Name, &lt.TotalTokens, &lt.CreatedAt, &lt.UpdatedAt, &lt.CurrentPrice,
			&lt.PropertyType, &lt.PropertySize, &lt.PropertySizeUnit, &lt.Landmark, &lt.DistanceFromLandmark,
			&lt.DistanceUnit, &lt.PropertyDescription, &lt.Latitude, &lt.Longitude,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan land token: %w", err)
		}

		// Fetch prices for the land token
		query := `
					SELECT id, date, value
					FROM prices
					WHERE land_token_id = ?;
	`

		rows, err := db.QueryContext(ctx, query, lt.LandID)
		if err != nil {
			return nil, fmt.Errorf("failed to query prices: %w", err)
		}
		defer rows.Close()

		var prices []*model.Price
		for rows.Next() {
			p := &model.Price{}
			err := rows.Scan(&p.ID, &p.Date, &p.Value)
			if err != nil {
				return nil, fmt.Errorf("failed to scan price: %w", err)
			}
			prices = append(prices, p)
		}

		if err := rows.Err(); err != nil {
			return nil, fmt.Errorf("rows error: %w", err)
		}

		lt.Prices = prices

		landTokens = append(landTokens, lt)
	}
	return landTokens, nil
}

// LandToken is the resolver for the landToken field.
func (r *queryResolver) LandToken(ctx context.Context, landID int32) (*model.LandToken, error) {
	db := r.Database

	query := `
		SELECT name, total_tokens, created_at, updated_at, current_price, property_type, property_size, property_size_unit, landmark, distance_from_landmark, distance_unit, property_description, latitude, longitude
		FROM land_tokens
		WHERE land_id = ?;
	`
	row := db.QueryRowContext(ctx, query, landID)
	lt := &model.LandToken{}
	err := row.Scan(
		&lt.Name, &lt.TotalTokens, &lt.CreatedAt, &lt.UpdatedAt, &lt.CurrentPrice,
		&lt.PropertyType, &lt.PropertySize, &lt.PropertySizeUnit, &lt.Landmark, &lt.DistanceFromLandmark,
		&lt.DistanceUnit, &lt.PropertyDescription, &lt.Latitude, &lt.Longitude,
	)

	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("land token not found")
	} else if err != nil {
		return nil, fmt.Errorf("failed to scan land token: %w", err)
	}

	// Fetch prices for the land token
	query = `
	SELECT id, date, value
	FROM prices
	WHERE land_token_id = ?;
	`
	rows, err := db.QueryContext(ctx, query, lt.LandID)
	if err != nil {
		return nil, fmt.Errorf("failed to query prices: %w", err)
	}
	defer rows.Close()

	var prices []*model.Price
	for rows.Next() {
		p := &model.Price{}
		err := rows.Scan(&p.ID, &p.Date, &p.Value)
		if err != nil {
			return nil, fmt.Errorf("failed to scan price: %w", err)
		}
		prices = append(prices, p)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("rows error: %w", err)
	}

	lt.Prices = prices

	return lt, nil
}

// Sales is the resolver for the sales field.
func (r *queryResolver) Sales(ctx context.Context) ([]*model.Sale, error) {
	db := r.Database // Assuming r.Database is your *sql.DB

	query := `
		SELECT s.id, s.quantity, s.price, s.created_at, s.land_token_id, s.seller_id
		FROM sales s;
		`

	rows, err := db.QueryContext(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("failed to query sales: %w", err)
	}
	defer rows.Close()

	var sales []*model.Sale
	for rows.Next() {
		s := &model.Sale{}
		var landTokenID int32
		var sellerID string
		err := rows.Scan(
			&s.ID, &s.Quantity, &s.Price, &s.CreatedAt, &landTokenID, &sellerID,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan sale: %w", err)
		}

		query := `
						SELECT land_id, name, total_tokens, created_at, updated_at, current_price, property_type, property_size, property_size_unit, landmark, distance_from_landmark, distance_unit, property_description, latitude, longitude
						FROM land_tokens
						WHERE land_id = ?;
		`
		row := db.QueryRowContext(ctx, query, landTokenID)
		lt := &model.LandToken{}
		err = row.Scan(
			&lt.LandID, &lt.Name, &lt.TotalTokens, &lt.CreatedAt, &lt.UpdatedAt, &lt.CurrentPrice,
			&lt.PropertyType, &lt.PropertySize, &lt.PropertySizeUnit, &lt.Landmark, &lt.DistanceFromLandmark,
			&lt.DistanceUnit, &lt.PropertyDescription, &lt.Latitude, &lt.Longitude,
		)

		if err == sql.ErrNoRows {
			return nil, fmt.Errorf("land token not found")
		} else if err != nil {
			return nil, fmt.Errorf("failed to scan land token: %w", err)
		}

		// Fetch prices for the land token
		query = `
		SELECT id, date, value
		FROM prices
		WHERE land_token_id = ?;
		`

		rows, err := db.QueryContext(ctx, query, lt.LandID)
		if err != nil {
			return nil, fmt.Errorf("failed to query prices: %w", err)
		}
		defer rows.Close()

		var prices []*model.Price
		for rows.Next() {
			p := &model.Price{}
			err := rows.Scan(&p.ID, &p.Date, &p.Value)
			if err != nil {
				return nil, fmt.Errorf("failed to scan price: %w", err)
			}
			prices = append(prices, p)
		}

		if err := rows.Err(); err != nil {
			return nil, fmt.Errorf("rows error: %w", err)
		}

		lt.Prices = prices

		s.LandToken = lt

		query = `
			SELECT
				u.public_key, u.username, u.phone, u.email, u.created_at, u.updated_at,
				r.id, r.name, r.description
			FROM users u
			LEFT JOIN user_roles ur ON u.public_key = ur.user_public_key
			LEFT JOIN roles r ON ur.role_id = r.id
			WHERE u.public_key = ?
		`

		rows, err = db.QueryContext(ctx, query, sellerID)
		if err != nil {
			return nil, fmt.Errorf("failed to fetch seller: %w", err)
		}
		defer rows.Close()

		var seller *model.User

		for rows.Next() {
			seller = &model.User{}
			role := &model.Role{}
			err := rows.Scan(&seller.PublicKey, &seller.Username, &seller.Email, &seller.Phone, &seller.CreatedAt, &seller.UpdatedAt, &role.ID, &role.Name, &role.Description)
			if err != nil {
				return nil, fmt.Errorf("failed to scan seller: %w", err)
			}
			seller.Roles = append(seller.Roles, role)
		}

		if seller == nil {
			return nil, fmt.Errorf("seller not found")
		}

		s.Seller = seller

		sales = append(sales, s)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("rows error: %w", err)
	}

	return sales, nil
}

// Sale is the resolver for the sale field.
func (r *queryResolver) Sale(ctx context.Context, id int) (*model.Sale, error) {
	db := r.Database

	query := `
 		SELECT s.id, s.quantity, s.price, s.created_at, s.land_token_id, s.seller_id
 		FROM sales s
 		WHERE s.id = ?;
 	`

	row := db.QueryRowContext(ctx, query, id)
	s := &model.Sale{}
	var landTokenID string
	var sellerID string
	err := row.Scan(
		&s.ID, &s.Quantity, &s.Price, &s.CreatedAt, &landTokenID, &sellerID,
	)

	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("sale not found")
	} else if err != nil {
		return nil, fmt.Errorf("failed to scan sale: %w", err)
	}

	query = `
 		SELECT land_id, name, total_tokens, created_at, updated_at, current_price, property_type, property_size, property_size_unit, landmark, distance_from_landmark, distance_unit, property_description, latitude, longitude
 		FROM land_tokens
 		WHERE land_id = ?;
 	`
	row = db.QueryRowContext(ctx, query, landTokenID)
	lt := &model.LandToken{}
	err = row.Scan(
		&lt.LandID, &lt.Name, &lt.TotalTokens, &lt.CreatedAt, &lt.UpdatedAt, &lt.CurrentPrice,
		&lt.PropertyType, &lt.PropertySize, &lt.PropertySizeUnit, &lt.Landmark, &lt.DistanceFromLandmark,
		&lt.DistanceUnit, &lt.PropertyDescription, &lt.Latitude, &lt.Longitude,
	)

	if err == sql.ErrNoRows {
		return nil, fmt.Errorf("land token not found")
	} else if err != nil {
		return nil, fmt.Errorf("failed to scan land token: %w", err)
	}

	query = `
 	SELECT id, date, value
 	FROM prices
 	WHERE land_token_id = ?;
 	`

	rows, err := db.QueryContext(ctx, query, lt.LandID)
	if err != nil {
		return nil, fmt.Errorf("failed to query prices: %w", err)
	}
	defer rows.Close()

	var prices []*model.Price
	for rows.Next() {
		p := &model.Price{}
		err := rows.Scan(&p.ID, &p.Date, &p.Value)
		if err != nil {
			return nil, fmt.Errorf("failed to scan price: %w", err)
		}
		prices = append(prices, p)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("rows error: %w", err)
	}

	lt.Prices = prices

	s.LandToken = lt

	query = `
 	SELECT
 	u.public_key, u.username, u.phone, u.email, u.created_at, u.updated_at,
 	r.id, r.name, r.description
 	FROM users u
 	LEFT JOIN user_roles ur ON u.public_key = ur.user_public_key
 	LEFT JOIN roles r ON ur.role_id = r.id
 	WHERE u.public_key = ?
 	`

	rows, err = db.QueryContext(ctx, query, sellerID)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch seller: %w", err)
	}
	defer rows.Close()

	var seller *model.User

	for rows.Next() {
		seller = &model.User{}
		role := &model.Role{}
		err := rows.Scan(&seller.PublicKey, &seller.Username, &seller.Email, &seller.Phone, &seller.CreatedAt, &seller.UpdatedAt, &role.ID, &role.Name, &role.Description)
		if err != nil {
			return nil, fmt.Errorf("failed to scan seller: %w", err)
		}
		seller.Roles = append(seller.Roles, role)
	}

	if seller == nil {
		return nil, fmt.Errorf("seller not found")
	}

	s.Seller = seller

	return s, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
